language: php

php:

  # aliased to 5.2.17
  - 5.2
  # aliased to a recent 5.3.x version
  - 5.3
  # aliased to a recent 5.4.x version
  - 5.4
  # aliased to a recent 5.5.x version
  - 5.5

script: phpunit --configuration phpunit_common.xml --coverage-text

#notifications:
#  irc: "irc.freenode.org#travis"